### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by shiinokinoki** [team-tissis/polylemma#126]
- BattleField
  - [ ] alice と bobを別名へ。できればmatchOrganizer側も併せていい名前に変えて統一したい。

- Dealer
  - stamina
    - [ ] underflow防ぐロジックを短くするために、maxStamina分余分にマージンを取ったところから引き算する実装に変更する

- Gacha
  - [ ] try-catchによるエラー処理をきれいに書こうとして結局中途ハンパになっていた気がする。汚いところがあれば直したい。

全体
- [ ] eventの命名をちゃんとイベントっぽい名前にしたい。名詞ではなく、hogeがhugaした（された）と何の処理が実施されたか明確になるように。

**Comment by terapoon** [comment]
Alice, Bob を Home, Visitor に名称変更

**Comment by terapoon** [comment]
FIXEDSLOT_NUM => FIXED_SLOTS_NUM

**Comment by terapoon** [comment]
WIN_COUNT = 3 での判定は、diffWinCount ベースの勝敗判定の subset なので削除

**Comment by terapoon** [comment]
BF contract で MO の address と interface を両方持っているのが冗長だったので削除
MO contract で BF の address と interface を両方持っているのが冗長だったので削除
既存のテストのパスとコンパイルの成功を確認済み

これに伴い、setBF, setMO 関数はそれぞれ contract address を渡して interface をセットする仕様に変更した。

また、address をみて IBF や IMO をサポートしているかを確認することが望ましいので、FIXME でコメントを残した。この部分は ERC165 の継承が必要だったりするので一旦放置している。

```
contract BF is ..., IERC165 {
...
function supportsInterface(bytes4 id) overrice(IERC165) ... {
    return id == type(IBF).interfaceId || super.supportsInterface(id);
}
...
```

みたいなノリで行けるはず。このリファクタで一緒にやってしまいたい。
MO に関しても同様。

**Comment by terapoon** [comment]
script file の名前が変なので rename した

**Comment by terapoon** [comment]
> BF contract で MO の address と interface を両方持っているのが冗長だったので削除 MO contract で BF の address と interface を両方持っているのが冗長だったので削除 既存のテストのパスとコンパイルの成功を確認済み
> 
> これに伴い、setBF, setMO 関数はそれぞれ contract address を渡して interface をセットする仕様に変更した。
> 
> また、address をみて IBF や IMO をサポートしているかを確認することが望ましいので、FIXME でコメントを残した。この部分は ERC165 の継承が必要だったりするので一旦放置している。
> 
> ```
> contract BF is ..., IERC165 {
> ...
> function supportsInterface(bytes4 id) overrice(IERC165) ... {
>     return id == type(IBF).interfaceId || super.supportsInterface(id);
> }
> ...
> ```
> 
> みたいなノリで行けるはず。このリファクタで一緒にやってしまいたい。 MO に関しても同様。

これに対応した
