### ISSUE TITLE
ラウンドの結果を返す処理について

### ISSUE THREAD

**Issue by hashi0203** [team-tissis/polylemma#135]
イベントは `uint8 indexed numRounds,` みたいに numRounds に indexed をつけて欲しい

関数については終わってないラウンドの結果を返さないで欲しい
今はラウンドが終わったかを判定せずにラウンドの番号までの結果全部を入れている

**Comment by terapoon** [comment]
_stepRound 関数を見ると、確定で numRounds++; が実行されているので、常にひとつ前のラウンドまでの結果を返すように変更しました。(これで行けとるはず)
