### ISSUE TITLE
charge 関数で課金額がいくらでも税率が 5% になってるかも…？

### ISSUE THREAD

**Issue by hashi0203** [team-tissis/polylemma#143]
フロントでそうなってるっぽいんやけど、確認してみて欲しい

**Comment by terapoon** [comment]
@hashi0203 @shiinokinoki 少なくとも forge test 段階では税率はきちんと上昇していることを確認

**Comment by terapoon** [comment]
これ、nokinoki により過去に解決済みのようでした。close します。
